version: "4" #версия докера

services: #контейнеры
  bot: #сам контейнер (его имя)
    build: # создание контейнера???
      context: ./ #рабочая основная (не контейнерская) папка
      dockerfile: Dockerfile # докер файл с которого создавать контейнер
    command: > # команда которую нужно выполнить
      /bin/sh -c 'python src/main1.py'
